### ISSUE TITLE
'New tab default' affects graph view behavior

### ISSUE THREAD

**Issue by sharik14** [aidan-gibson/obsidian-opener#9]
Hello - I use Opener constantly now and it's been great. I've just started using the 'local graph' feature, however, and am finding an issue with opener. Not sure if this can be fixed, but thought I would mention this as a feature request here.

Issue: If I have 'new tab default' turned off (i.e. not using Opener), then single-(left)-clicking a node in the graph opens the target/new node's local graph in the same window. This is great!  I can explore/traverse the local graph and find connections quickly.  But with Opener's 'new tab default' turned on, clicking a node opens a new tab in the same right sidebar as the graph, which is not really what you want. (You can right-click the target and choose 'show local graph' but even that proliferates new columns and is hard to use.)

I noticed this comment in your notes:

> Graph view command doesn't open in new tab, it doesn't use openFile(). I have provided command 'Open Graph View in new tab' you can reassign Ctrl/Cmd + G to.

-- but I don't think that helps you click around the graph. I'm wondering if it would be possible to add a new Opener setting to change the graph view behavior back to the default. Is this even possible? Not sure if the APIs allow this to be fixed.

Thanks!

**Comment by lukemt** [comment]
Hi @sharik14,

At first I thought I couldn't reproduce it, because I keep the local graph in the actual right sidebar. There everything works as you would expect, see video below. 

But now I understand what you are doing and I see the problem. It's a strange situation because the tabs are linked together in this case. Maybe we should disable opener for graph views or linked tabs altogether. Question is how do we even know? I'm debugging this but couldn't even find any clues yet.

I attached a video of my setup for your enjoyment ;) :

https://github.com/aidan-gibson/obsidian-opener/assets/3893274/27528cc2-1017-46da-9aa3-92635d484537

**Comment by lukemt** [comment]
Maybe it's best to disable the opener functionality for linked tabs (like local graph views). Linked tabs are awkward and we can't fix that IMO, but reverting to the default behaviour may be the best option. 

To explore "Linked Tabs" right-click on a tab and select one of the "Open linked view" options.
